### ISSUE TITLE
Error when running script on SuperMicro

### ISSUE THREAD

**Issue by jczmok-iag** [Solvik/netbox-agent#114]
sh# netbox_agent --debug -c /etc/netbox_agent.yaml
 
Traceback (most recent call last):
  File "/usr/local/bin/netbox_agent", line 11, in <module>
    load_entry_point('netbox-agent==0.5.1.dev3+gbb7c8c8', 'console_scripts', 'netbox_agent')()
  File "/usr/local/lib/python3.7/dist-packages/netbox_agent-0.5.1.dev3+gbb7c8c8-py3.7.egg/netbox_agent/cli.py", line 39, in main
    return run(config)
  File "/usr/local/lib/python3.7/dist-packages/netbox_agent-0.5.1.dev3+gbb7c8c8-py3.7.egg/netbox_agent/cli.py", line 21, in run
    manufacturer = dmidecode.get_by_type('Chassis')[0].get('Manufacturer')
TypeError: get_by_type() missing 1 required positional argument: 'type_id'

dmideode reports:
root@inet-xen-215-13:/netbox/netbox-agent/netbox_agent# dmidecode -t chassis
# dmidecode 3.2
Getting SMBIOS data from sysfs.
SMBIOS 2.7 present.

Handle 0x0003, DMI type 3, 22 bytes
Chassis Information
	Manufacturer: Supermicro
	Type: Desktop
	Lock: Not Present
	Version: 0123456789
	Serial Number: 0123456789
	Asset Tag: To Be Filled By O.E.M.
	Boot-up State: Safe
	Power Supply State: Safe
	Thermal State: Safe
	Security Status: None
	OEM Information: 0x00000000
	Height: Unspecified
	Number Of Power Cords: 1
	Contained Elements: 0
	SKU Number: To be filled by O.E.M.

**Comment by jczmok-iag** [comment]
Please advise what's not working here or what i did wrong

**Comment by Solvik** [comment]
Hello,

Seems we broke the agent while merging tests branches
I'm fixing it right now

**Comment by jczmok-iag** [comment]
good to know. when is the code updated?

Von meinem iPhone gesendet

**Comment by jczmok-iag** [comment]
ah i saw it in the fix branch. okay next bug..
