### ISSUE TITLE
_choices deprecated

### ISSUE THREAD

**Issue by martydingo** [Solvik/netbox-agent#126]
Hiya there,

Trying to run this, it causes an error due to the _choices being removed in Netbox v2.8.0, as listed here
https://github.com/netbox-community/netbox/issues/3416

So currently when updating I see the error *api/dcim/_choices/ could not be found.

Can we update to use the new OPTIONS method?

**Comment by Solvik** [comment]
Hi !

Thanks, I'll take a look today and commit a fix
