### ISSUE TITLE
Add documentation on how to invoke the agent

### ISSUE THREAD

**Issue by HeLiBloks** [Solvik/netbox-agent#133]
I suggest that an example be added that shows how to invoke the netbox-agent from the cli and/or Python shell.
I believe this would make the user-base larger.

**Comment by Solvik** [comment]
Hi @HeLiBloks 

Thanks for opening the issue !
I've added some infos in the README in #134 

Is there something else you wish I added?

**Comment by Solvik** [comment]
Let's say it is :-)

**Comment by HeLiBloks** [comment]
Thank you.
