### ISSUE TITLE
config.py does not support netbox url with self-signed certificates

### ISSUE THREAD

**Issue by strus38** [Solvik/netbox-agent#147]
Hi
could you update config.py, so it can work with self-signed certificates?
Proposal:
- add an option to netbox-agent: --ignore-ssl-verify

Modifications (in addition of adding the option):
- in config.py line line 1
```
import requests
import urllib3
urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)
```
then line 80:
```
if (no_ssl_verify):
    session = requests.Session()
    session.verify = False

nb = pynetbox.api(
     url=get_config().netbox.url,
     token=get_config().netbox.token
)
if (no_ssl_verify):
    nb.http_session = session
return nb
```

Thanks!

**Comment by Solvik** [comment]
If you're able to propose a PR and test it, that would be very nice :)

**Comment by strus38** [comment]
The PR 152 is opened. Feel free to merge or comment it.
Thanks!

**Comment by Solvik** [comment]
many thanks for this addition !

**Comment by strus38** [comment]
Don't know how to fix the flake8 error. I let you fix it for me if you can.

**Comment by Solvik** [comment]
#152 merged!
