### ISSUE TITLE
Supermicro - divice mis-identification 

### ISSUE THREAD

**Issue by wolfman2g1** [Solvik/netbox-agent#149]
the agent is recognizing Supermicro SYS-1029U-E1CRTP-2-LL09G as a chassis.  This should be a 1U service not a chassis.  Is there a specific override that I can set in the config file? I don't have any chassis in my infra. 

Also identifying any servers with motherboard  X11SPW-TF as a blade.

**Comment by Solvik** [comment]
It's because of this code line: 
https://github.com/Solvik/netbox-agent/blob/master/netbox_agent/vendors/supermicro.py#L27

We should be more specific in the detection of blade or not based on the product number. Do you have more information for that ?

Forcing server or blade with the command line could be a nice addition I'll open an issue for that

**Comment by wolfman2g1** [comment]
Sure what kind of information do you need? Also do you need help with the project?

**Comment by Solvik** [comment]
The blade detection system is based per manufacturer.
With manufacturers like Dell, it's pretty easy, blade's product number always begins with `MXXX` (M610, M640 etc)

It's also true with HP, but I have a feeling that it's less easy with Supermicro... they tend to have false dmidecode infos and their product number doesn't reflect the "am I a blade or a pizza box" part

If you have a better understanding of their products and know a generic way to check that, I'd be very happy to implement it !

Regarding help with the project, it's more than welcome ! It was a personal project that I thought could be interesting for other netbox user, so I'm always happy to implement or merge additional features!

**Comment by wolfman2g1** [comment]
All the supermicro servers i've used in the past few years start with SYS including their microcloud( these considered blades?).

**Comment by Solvik** [comment]
Microcloud are considered blade from my point of view, especially if dmidecode mentions a `Slot`

**Comment by wolfman2g1** [comment]
From what I've noticed their product numbers aren't something that's predictable. I think to handle that programmatically would be difficult( at least for me). I have someone working with me to look at solutions. But I think being able to pass an option like is_blade: True|False when the detected vendor is supermicro may be an easy way to do it.

**Comment by Solvik** [comment]
I understand

The agent will need to know the S/N of the chassis to do the lookup, and its blade slot to correctly assign the server to the blade.

I will see if I can work on this additional feature this week

**Comment by Solvik** [comment]
It adds more complexity to the agent, so I preferred to rework the supermicro blade/pizza detection, would you be able to try the branch `supermicro`?

**Comment by wolfman2g1** [comment]
I can try bright and early on Monday.

ryan.jones26@gmail.com

**Comment by wolfman2g1** [comment]
I'm free to test the branch today. which branch should I test ?

**Comment by Solvik** [comment]
This one : https://github.com/Solvik/netbox-agent/tree/supermicro

Le lun. 13 juil. 2020 à 19:58, Ryan Jones <notifications@github.com> a
écrit :

**Comment by wolfman2g1** [comment]
I assume i need to pass an option

  ```
 if self.is_blade():
  File "/tmp/netbox/netbox_agent/vendors/supermicro.py", line 26, in is_blade
    product_name = self.get_product_name()
  File "/tmp/netbox/netbox_agent/vendors/supermicro.py", line 52, in get_product_name
    if self.is_blade():
  File "/tmp/netbox/netbox_agent/vendors/supermicro.py", line 26, in is_blade
    product_name = self.get_product_name()
  File "/tmp/netbox/netbox_agent/vendors/supermicro.py", line 52, in get_product_name
    if self.is_blade():
  File "/tmp/netbox/netbox_agent/vendors/supermicro.py", line 26, in is_blade
    product_name = self.get_product_name()
RecursionError: maximum recursion depth exceeded

```

**Comment by Solvik** [comment]
No, I just forgot I didn't implement supermicro server compatibilty
I've checked the code and fixed some stuff and added more tests

I got a dmidecode of a some kind of blade system to test it 

Could you retry?

**Comment by wolfman2g1** [comment]
seems better. still getting an error.
 ```
File "/tmp/netbox/netbox_agent/cli.py", line 39, in run
    server.netbox_create_or_update(config)
  File "/tmp/netbox/netbox_agent/server.py", line 306, in netbox_create_or_update
    if server.name != self.get_hostname():
AttributeError: 'NoneType' object has no attribute 'name'
```
will use the new branch to test other systems. but the box I just tested on is a model that I was having the issue with previously

**Comment by wolfman2g1** [comment]
deployed on another 6 boxes. All throw the error above however everything else seems to be working fine.

**Comment by Solvik** [comment]
You're not the first one to raise this error to me, what netbox version are you using ?

**Comment by wolfman2g1** [comment]
v2.8.6
Ryan
3476787719
ryan.jones26@gmail.com

**Comment by Solvik** [comment]
I'm closing this issue since I've merge the supermicro modifications
I'll open another to fix the `server.anme` problem
