### ISSUE TITLE
Ignored interfaces / IPs / etc shouldn't be deleted from Netbox

### ISSUE THREAD

**Issue by nrhtr** [Solvik/netbox-agent#167]
**Describe the bug**
Interfaces / IP addresses that exist in Netbox but not on the local device are deleted even if they're included in the "ignore_*" regex in the config.

**Expected behavior**
I would expect netbox-agent not to touch ignored items.

**Configuration file**
```
# Network configuration
network:
  # Regex to ignore interfaces
  ignore_interfaces: "(dummy.*|docker.*|bond.*|idrac|ipmi|lo|loopback|local|veth.*)"
```

**Environment:**
N/A

**Additional context**
N/A

**Comment by Solvik** [comment]
There was an issue with the `jsonargparse` dependency that made this argument ignored
Can you tell me the version of `netbox-agent` and `jsonargparse` you're using so I can try to reproduce?
