### ISSUE TITLE
Support netbox 2.9

### ISSUE THREAD

**Issue by Solvik** [Solvik/netbox-agent#176]
Would fix #175

**Comment by jjgraham** [comment]
Any chance netbox-agent can be made to work with netbox v2.10?
I am getting errors parsing the output of lldpctl because of "Unknown TLVs"

**Comment by Solvik** [comment]
Hi @jjgraham 

I still have a working branch with netbox 2.9 but haven't had the time to thoroughly test it
I need to assess the changes for netbox 2.10 too 

Sorry for not being able to keep up, I've been very busy

**Comment by gjvc** [comment]
I will help for testing on netbox 2.10

**Comment by KivraChristoffer** [comment]
Have done some testing and send in a patch to make virtual work.
We will send one in later that fixes issues with reporting memory.
