### ISSUE TITLE
Issue with handling virtual interfaces

### ISSUE THREAD

**Issue by KivraChristoffer** [Solvik/netbox-agent#193]
DEBUG:urllib3.connectionpool:https://netbox.prod.kivra.net:443 "GET /api/virtualization/interfaces/23/ HTTP/1.1" 200 386
Traceback (most recent call last):
  File "/usr/local/bin/netbox_agent", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/netbox_agent/cli.py", line 44, in main
    return run(config)
  File "/usr/local/lib/python3.6/site-packages/netbox_agent/cli.py", line 39, in run
    server.netbox_create_or_update(config)
  File "/usr/local/lib/python3.6/site-packages/netbox_agent/virtualmachine.py", line 104, in netbox_create_or_update
    self.network.create_or_update_netbox_network_cards()
  File "/usr/local/lib/python3.6/site-packages/netbox_agent/network.py", line 416, in create_or_update_netbox_network_cards
    if not interface.type or \
  File "/usr/local/lib/python3.6/site-packages/pynetbox/core/response.py", line 196, in __getattr__
    raise AttributeError('object has no attribute "{}"'.format(k))
AttributeError: object has no attribute "type"

The virtual interface dont have "type" as it says

**Comment by hiddenman** [comment]
I've got the same problems within virtual machine running Netbox:

```
INFO:root:Interface None not found, creating..
INFO:root:Creating NIC lo (None) on netbox
DEBUG:urllib3.connectionpool:https://192.168.110.162:443 "POST /api/virtualization/interfaces/ HTTP/1.1" 201 479
DEBUG:urllib3.connectionpool:https://192.168.110.162:443 "GET /api/virtualization/interfaces/5/ HTTP/1.1" 200 479
Traceback (most recent call last):
  File "/opt/netbox/venv/bin/netbox_agent", line 8, in <module>
    sys.exit(main())
  File "/opt/netbox/venv/lib/python3.9/site-packages/netbox_agent/cli.py", line 44, in main
    return run(config)
  File "/opt/netbox/venv/lib/python3.9/site-packages/netbox_agent/cli.py", line 39, in run
    server.netbox_create_or_update(config)
  File "/opt/netbox/venv/lib/python3.9/site-packages/netbox_agent/virtualmachine.py", line 104, in netbox_create_or_update
    self.network.create_or_update_netbox_network_cards()
  File "/opt/netbox/venv/lib/python3.9/site-packages/netbox_agent/network.py", line 416, in create_or_update_netbox_network_cards
    if not interface.type or \
  File "/opt/netbox/venv/lib/python3.9/site-packages/pynetbox/core/response.py", line 196, in __getattr__
    raise AttributeError('object has no attribute "{}"'.format(k))
AttributeError: object has no attribute "type"
```

This happens with any type of interface (lo, eth0 and so on).

**Comment by KivraChristoffer** [comment]
I where using the wrong branch sins we have a more modern netbox installation.. take a look at the MR's

**Comment by hiddenman** [comment]
Actually, the problem still exists in the latest netbox 3.0.3 inside the virtual machine and i managed to fix it using hasattr() check like this:

netbox_agent/network.py:416:
```
            if not hasattr(interface,'type') or not interface.type or \
```

**Comment by hiddenman** [comment]
After that i got another problem with IPv6 address on the virtual machine's interface:

```
DEBUG:urllib3.connectionpool:https://192.168.110.162:443 "GET /api/virtualization/interfaces/7/ HTTP/1.1" 200 479
INFO:root:Interface type is wrong, resetting
DEBUG:urllib3.connectionpool:https://192.168.110.162:443 "GET /api/ipam/ip-addresses/?address=%3A%3A1%2F128 HTTP/1.1" 200 52
INFO:root:Create new IP ::1/128 on lo
DEBUG:urllib3.connectionpool:https://192.168.110.162:443 "POST /api/ipam/ip-addresses/ HTTP/1.1" 400 39
Traceback (most recent call last):
  File "/opt/netbox/venv/bin/netbox_agent", line 8, in <module>
    sys.exit(main())
  File "/opt/netbox/venv/lib/python3.9/site-packages/netbox_agent/cli.py", line 44, in main
    return run(config)
  File "/opt/netbox/venv/lib/python3.9/site-packages/netbox_agent/cli.py", line 39, in run
    server.netbox_create_or_update(config)
  File "/opt/netbox/venv/lib/python3.9/site-packages/netbox_agent/virtualmachine.py", line 104, in netbox_create_or_update
    self.network.create_or_update_netbox_network_cards()
  File "/opt/netbox/venv/lib/python3.9/site-packages/netbox_agent/network.py", line 445, in create_or_update_netbox_network_cards
    self.create_or_update_netbox_ip_on_interface(ip, interface)
  File "/opt/netbox/venv/lib/python3.9/site-packages/netbox_agent/network.py", line 316, in create_or_update_netbox_ip_on_interface
    netbox_ip = nb.ipam.ip_addresses.create(
  File "/opt/netbox/venv/lib/python3.9/site-packages/pynetbox/core/endpoint.py", line 278, in create
    req = Request(
  File "/opt/netbox/venv/lib/python3.9/site-packages/pynetbox/core/query.py", line 383, in post
    return self._make_call(verb="post", data=data)
  File "/opt/netbox/venv/lib/python3.9/site-packages/pynetbox/core/query.py", line 274, in _make_call
    raise RequestError(req)
pynetbox.core.query.RequestError: The request failed with code 400 Bad Request: {'status': ['1 is not a valid choice.']}
```

**Comment by KivraChristoffer** [comment]
https://github.com/Solvik/netbox-agent/pull/194  that solved it for us.
If i dont recall it wrong that seems like issues for the older versions of netbox-agent. not the 2.9 branch.

**Comment by hiddenman** [comment]
> [#191 (comment)](https://github.com/Solvik/netbox-agent/issues/191#issuecomment-911370840) here might be to some help also .

@KivraChristoffer Thank you!

1. Do you mean i have to apply this commit: https://github.com/Solvik/netbox-agent/pull/194/commits/258f5c531faa84d4518f3bd2f0588eed5faa2070  ?
2. Is there any newest branch?  
3. Didn't understand where you'd changed the  ' status=1' to 'status="active"

Thank you.

**Comment by hiddenman** [comment]
@KivraChristoffer This pull request refers to the branch 2.9. Should i use it?  
Now sure how to use it with pypi.org as it has the master branch distribution.

**Comment by hiddenman** [comment]
@KivraChristoffer I see commits you mentioned:
https://github.com/Solvik/netbox-agent/commits/176-netbox-2.9

However, the master branch has recent commits, while 2.9 branch is stale.

So what version should i use?

Thank you.

**Comment by KivraChristoffer** [comment]
we are using : https://github.com/Solvik/netbox-agent/pull/177
and with this ( might be able to take this with everything directly,( i am no git pro :) ) :https://github.com/Solvik/netbox-agent/pull/194.
this is working for us against netbox 3.0.1

**Comment by hiddenman** [comment]
> we are using : #177
> and with this ( might be able to take this with everything directly,( i am no git pro :) ) :#194.
> this is working for us against netbox 3.0.1

Correct me if i'm wrong: you just took the sources of this branch:  https://github.com/Solvik/netbox-agent/tree/176-netbox-2.9   and use it as netbox-agent python package , right? Or you applied some commits from this branch to your master branch?

**Comment by hiddenman** [comment]
@KivraChristoffer Just tried this branch and got another error:

```
INFO:root:Interface None not found, creating..
INFO:root:Creating NIC lo (None) on netbox
DEBUG:urllib3.connectionpool:https://192.168.110.162:443 "POST /api/virtualization/interfaces/ HTTP/1.1" 201 479
Traceback (most recent call last):
  File "/opt/netbox/venv/bin/netbox_agent", line 8, in <module>
    sys.exit(main())
  File "/opt/netbox/venv/lib/python3.9/site-packages/netbox_agent/cli.py", line 51, in main
    return run(config)
  File "/opt/netbox/venv/lib/python3.9/site-packages/netbox_agent/cli.py", line 46, in run
    server.netbox_create_or_update(config)
  File "/opt/netbox/venv/lib/python3.9/site-packages/netbox_agent/virtualmachine.py", line 104, in netbox_create_or_update
    self.network.create_or_update_netbox_network_cards()
  File "/opt/netbox/venv/lib/python3.9/site-packages/netbox_agent/network.py", line 445, in create_or_update_netbox_network_cards
    ret, interface = self.reset_vlan_on_interface(nic, interface)
  File "/opt/netbox/venv/lib/python3.9/site-packages/netbox_agent/network.py", line 217, in reset_vlan_on_interface
    interface = self.nb_net.interfaces.get(id=interface.id)
  File "/opt/netbox/venv/lib/python3.9/site-packages/pynetbox/core/endpoint.py", line 138, in get
    filter_lookup = self.filter(**kwargs)
  File "/opt/netbox/venv/lib/python3.9/site-packages/pynetbox/core/endpoint.py", line 211, in filter
    raise ValueError(
ValueError: A reserved ('id', 'pk', 'limit', 'offset') kwarg was passed. Please remove it try again.
```

Strange. Not sure what to use. It's better to ask @Solvik  :)

**Comment by hiddenman** [comment]
@KivraChristoffer ANd please help me with this: https://github.com/Solvik/netbox-agent/issues/191  Where did you change 1 to active?

**Comment by hiddenman** [comment]
> @KivraChristoffer Just tried this branch and got another error:
> 
> ```
> INFO:root:Interface None not found, creating..
> INFO:root:Creating NIC lo (None) on netbox
> DEBUG:urllib3.connectionpool:https://192.168.110.162:443 "POST /api/virtualization/interfaces/ HTTP/1.1" 201 479
> Traceback (most recent call last):
>   File "/opt/netbox/venv/bin/netbox_agent", line 8, in <module>
>     sys.exit(main())
>   File "/opt/netbox/venv/lib/python3.9/site-packages/netbox_agent/cli.py", line 51, in main
>     return run(config)
>   File "/opt/netbox/venv/lib/python3.9/site-packages/netbox_agent/cli.py", line 46, in run
>     server.netbox_create_or_update(config)
>   File "/opt/netbox/venv/lib/python3.9/site-packages/netbox_agent/virtualmachine.py", line 104, in netbox_create_or_update
>     self.network.create_or_update_netbox_network_cards()
>   File "/opt/netbox/venv/lib/python3.9/site-packages/netbox_agent/network.py", line 445, in create_or_update_netbox_network_cards
>     ret, interface = self.reset_vlan_on_interface(nic, interface)
>   File "/opt/netbox/venv/lib/python3.9/site-packages/netbox_agent/network.py", line 217, in reset_vlan_on_interface
>     interface = self.nb_net.interfaces.get(id=interface.id)
>   File "/opt/netbox/venv/lib/python3.9/site-packages/pynetbox/core/endpoint.py", line 138, in get
>     filter_lookup = self.filter(**kwargs)
>   File "/opt/netbox/venv/lib/python3.9/site-packages/pynetbox/core/endpoint.py", line 211, in filter
>     raise ValueError(
> ValueError: A reserved ('id', 'pk', 'limit', 'offset') kwarg was passed. Please remove it try again.
> ```
> 
> Strange. Not sure what to use. It's better to ask @Solvik :)

This one was caused by old pynetbox, upgraded it to the 6.1.3 and everything became correct. The only question is about 1=>active.

**Comment by KivraChristoffer** [comment]
> @KivraChristoffer ANd please help me with this: #191 Where did you change 1 to active?



> > we are using : #177
> > and with this ( might be able to take this with everything directly,( i am no git pro :) ) :#194.
> > this is working for us against netbox 3.0.1
> 
> Correct me if i'm wrong: you just took the sources of this branch: https://github.com/Solvik/netbox-agent/tree/176-netbox-2.9 and use it as netbox-agent python package , right? Or you applied some commits from this branch to your master branch?

Yes we used that one .. found a issue that we send a  MR about: https://github.com/Solvik/netbox-agent/pull/194 its a simple fix.
I will take a look to see if we did any change to the status, but i think that with 2.9  release that where the only thing we changed.

**Comment by KivraChristoffer** [comment]
> > we are using : #177
> > and with this ( might be able to take this with everything directly,( i am no git pro :) ) :#194.
> > this is working for us against netbox 3.0.1
> 
> Correct me if i'm wrong: you just took the sources of this branch: https://github.com/Solvik/netbox-agent/tree/176-netbox-2.9 and use it as netbox-agent python package , right? Or you applied some commits from this branch to your master branch?

Are you installing it via pip or git ?

**Comment by KivraChristoffer** [comment]
i did test to run with lo interface and it worked.
I would guess you have wrong requirements installed  or its related to python 3.9.
if you want shoot me a email and i can send the tar for what we are using if you like to check it out.

**Comment by KivraChristoffer** [comment]
i am so bad @ git, but i did a test and made a fork that you might test.
https://github.com/KivraChristoffer/netbox-agent/tree/176-netbox-2.9
this one i did just run and it works for us.

**Comment by KivraChristoffer** [comment]
> This one was caused by old pynetbox, upgraded it to the 6.1.3 and everything became correct. The only question is about 1=>active.

This is due to you are not using the right network.py file.  make sure you change branch after cloning.

**Comment by hiddenman** [comment]
@KivraChristoffer Thank you. I updated the pynetbox and switched to the 2.9 branch of the netbox-agent and everything seems to be working fine.

However, the master branch has some more bugfixes and improvements.

**Comment by KivraChristoffer** [comment]
@hiddenman  NP :)
I am posting updates to my branch as it seems these guys are still on vacay :)

**Comment by KivraChristoffer** [comment]
I will close this, as newer releases have solved this
