### ISSUE TITLE
Cant create PR, Please add QEMU as a virtual server manufacture 

### ISSUE THREAD

**Issue by KivraChristoffer** [Solvik/netbox-agent#210]
in virtualmachine.py
change from this:
`       'VirtualBox' in bios[0]['Version'] or \
       'VMware' in system[0]['Manufacturer']:
        return True
`
to this:
`       'VirtualBox' in bios[0]['Version'] or \
       'QEMU' in system[0]['Manufacturer']or \
       'VMware' in system[0]['Manufacturer']:
        return True
`
We have been running with that last months and so far no issues with it

**Comment by cyrinux** [comment]
Thanks @KivraChristoffer its done

**Comment by KivraChristoffer** [comment]
Could you please also add it to 2.9 branch  ?
