### ISSUE TITLE
Hp raid, issue when second raidcard dont have any drives attached

### ISSUE THREAD

**Issue by KivraChristoffer** [Solvik/netbox-agent#217]
We have a solution and is going to push it today
@cyrinux so maybe we can have release 0.7.3 today :)

**Comment by KivraChristoffer** [comment]
#218

**Comment by cyrinux** [comment]
@KivraChristoffer thanks, please find https://github.com/Solvik/netbox-agent/pull/220 that make the code more readable and prevent loosing some `!= 0` errors.  Its a review from @geektophe .

**Comment by KivraChristoffer** [comment]
will close this, as fix is in the loop
