### ISSUE TITLE
New release to PyPI

### ISSUE THREAD

**Issue by DeathRabbit679** [Solvik/netbox-agent#229]
The README.md install instructions just show using pip to install netbox-agent from  PyPI, but it looks like the last few releases aren't posted there it seems. The latest release is 0.6.2 from 2020. I've just been playing around with netbox-agent by installing the tar from github, so far.

**Comment by CodeBleu** [comment]
bump @Solvik :point_up:

**Comment by Solvik** [comment]
Hi !

Sorry for being idle here 
I've just released the lastest version :)
