### ISSUE TITLE
VM modules requests dcim/interfaces instead of virtualization/interface for getting the interface name

### ISSUE THREAD

**Issue by Metrax** [Solvik/netbox-agent#235]
Hi,

the virtual machine module is making a request to the dcim/interfaces api to get the interface name:

DEBUG:urllib3.connectionpool:https://netbox.lab.xxx:443 "GET /api/virtualization/interfaces/?mac_address=92%3Axx%3Axx%3A8a%3A1a%3Ae5&name=ens18&virtual_machine_id=140&limit=0 HTTP/1.1" 200 688
DEBUG:urllib3.connectionpool:https://netbox.lab.xxx:443 "GET /api **/dcim/** interfaces/?id=241&limit=0 HTTP/1.1" 200 1408
DEBUG:urllib3.connectionpool:https://netbox.lab.xxx:443 "GET /api/ipam/ip-addresses/?address=213.xxx.xx.x%2F27&limit=0 HTTP/1.1" 200 1045
DEBUG:urllib3.connectionpool:https://netbox.lab.xxx:443 "GET /api/ipam/ip-addresses/595/ HTTP/1.1" 200 993
INFO:root:Assigning existing IP 213.xxx.xx.x/27 to **GigabitEthernet1/0/16**

The correct call would be:
GET /api **/virtualization/** interfaces/?id=241&limit=0

I didn't notice any other impact of this, instead of that the logging is incorrect.

**Comment by KivraChristoffer** [comment]
Its this not a duplicate of #226 ?
( is having a pr also)

**Comment by Metrax** [comment]
@KivraChristoffer
I'm not sure if it is the same problem, but the PR is fixing my problem.
Hopefully it can be mereged to the main-branch soon.
