### ISSUE TITLE
error on IPMI interface

### ISSUE THREAD

**Issue by buzzzo** [Solvik/netbox-agent#238]
Last version of netbox-agent
Last version of netbox

when register it gives the following: error
 raise RequestError(req)
pynetbox.core.query.RequestError: The request failed with code 400 Bad Request: {'address': ['Cannot create IP address with /0 mask.']}

Related to: INFO:root:Create new IP 0.0.0.0/0 on IPMI

Seems that netbox does not like interface with 0.0.0.0/0 address.
I have tried to filter out the IPMI interface on conf file but seems that the filter is not considered.
Would be better to from netbox-agent side to ignore interface without ip or with 0.0.0.0/0 ip and don't try to pass it to netbox

**Comment by Solvik** [comment]
Hi @buzzzo 

Could you paste the output of `ipmitool lan print` output ?

I think your IPMI is not configured to get an IP
That should not be a problem but we may need to implement this case in the netbox-agent code
