### ISSUE TITLE
Several fields on the cable API serializers have been altered or removed to support multiple-object cable terminations

### ISSUE THREAD

**Issue by bds-congnguyen** [Solvik/netbox-agent#240]
**Describe the bug**
The Netbox api fields was changed from version 3.3.0 and it cause error
```AttributeError: object has no attribute "termination_b"```

**Expected behavior**

**Configuration file**

**Environment:**
 - Netbox agent version: master
- Netbox: v3.3.1
**Additional context**
Details of API fields listed at here https://github.com/netbox-community/netbox/releases/tag/v3.3.0

**Comment by Solvik** [comment]
Hi @bds-congnguyen 

Thanks for the issue

Unfortunately, netbox-agent is not yet compatible with Netbox 3.3 which introduces lots of changes in the cable API 

You should disable the LLDP feature from the agent while I, or a contributor, make the necessary modifications

Thanks !

**Comment by debdolph** [comment]
https://github.com/netbox-community/pynetbox/issues/491

**Comment by KivraChristoffer** [comment]
So now pynetbox is released with support for 3.3.
