### ISSUE TITLE
netbox 3.3.9

### ISSUE THREAD

**Issue by KivraChristoffer** [Solvik/netbox-agent#258]
As they changed some facts, i get this when running on a physical server.
AttributeError: object has no attribute "termination_b".

Will investigate to see if i can solve it .

**Comment by bds-congnguyen** [comment]
https://github.com/Solvik/netbox-agent/issues/240

**Comment by KivraChristoffer** [comment]
Thanx

**Comment by KivraChristoffer** [comment]
Duplicate
