### ISSUE TITLE
lldm.py return error:  current_dict[final] = value,  TypeError

### ISSUE THREAD

**Issue by Zagrebelsky** [Solvik/netbox-agent#274]
Hi!
It looks like there might be an issue when the path_component is already a string in the dictionary. 
When this happens, current_dict becomes a string, and then current_dict[final] = value, it throws the TypeError.

```
  File "/netbox_agent/lldp.py", line 45, in parse
    current_dict[final] = value
```

**Expected behavior**
current_dict should always be dict, and not failed

**Environment:**
 - OS: [e.g. Rocky 8 18.04]
 - Netbox agent version [v0.7.2]

I prepared fix.

- in [lldp.py line line 34 and 35](https://github.com/Solvik/netbox-agent/blob/master/netbox_agent/lldp.py#LL34C1-L35C60)
```
                current_dict[path_component] = current_dict.get(path_component, {})
                current_dict = current_dict[path_component]
```
replace to
```
                if not isinstance(current_dict.get(path_component), dict):
                    current_dict[path_component] = {}
                current_dict = current_dict.get(path_component)
```

Thanks!

**Comment by Zagrebelsky** [comment]
done https://github.com/Solvik/netbox-agent/pull/280

**Comment by Solvik** [comment]
Thanks !
