### ISSUE TITLE
netbox_agent==0.7.2 not available on pip

### ISSUE THREAD

**Issue by mkhelifa** [Solvik/netbox-agent#298]
Hello, 

seems that the latest available release 0.7.2 is not available in pypi.org. https://pypi.org/project/netbox-agent/

Could you make this happen please ?

Thanks

**Comment by mkhelifa** [comment]
The setup.py is actually mentioning 0.7.1 as of pypi. I don't know if it s meant to be synced with you relases

**Comment by ribetm** [comment]
As development is starting again on this repo, we are planning on adding automated releases. Hopefully 0.7.2 and more should be released soon !

**Comment by CllaudiaB** [comment]
Hello,
netbox-agent v0.7.2 is available in pypi.org
netbox-agent v0.7.2 is compatible with Netbox  verison 2.9 up to 3.0, we're working on adding compatibility with the latest versions.

**Comment by mariano-daniel** [comment]
Thank you so much! We're looking forward to the new version compatibility! Please make sure to list your ko-fi.com or paypal account for donations. Thanks!
