### ISSUE TITLE
Proyect hasn't been updated in a year. Anyone know of a current fork?

### ISSUE THREAD

**Issue by mariano-daniel** [Solvik/netbox-agent#300]
Proyect hasn't been updated in a year. Anyone know of a current fork?

**Comment by n1nj444** [comment]
Same question here, I'm trying to set up the agent as a script on my end.

**Comment by CllaudiaB** [comment]
Hello @mariano-daniel  @n1nj444 
This month we're going to start working on the project again and update it.

**Comment by mariano-daniel** [comment]
Thanks for the update @CllaudiaB ! I will be watching the project!
